--- #YAML:1.0
name:                CPAN-Checksums
version:             1.064
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.3601
distribution_type:   module
requires:     
    Compress::Bzip2:               0
    Compress::Zlib:                0
    Data::Compare:                 0
    Data::Dumper:                  0
    Digest::MD5:                   0
    Digest::SHA:                   0
    DirHandle:                     0
    File::Spec:                    0
    File::Temp:                    0
    IO::File:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
